name: CI Workflow for MyProject

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: Clean previous build and cache
      run: |
        if [ -d build ]; then
          rm -rf build
        fi
        mkdir build
        cd build
        rm -f CMakeCache.txt

    - name: Configure CMake
      run: |
        cd build
        cmake ..

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: cd build && ctest --output-on-failure
